# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb0bf33043217287fa5e44fc2471c963f8f5af79a0f3d89b40b536838e950ae55a1b81adb2e5f9370a4c5e85f60adb574e21932d5cd017fd344820e24addcc4

test:
  secret_key_base: b4c91757e39e480579bde7a8b618395548dcfdc46ae3c912f7e362598bf482a5af4771389fc00745b11f7f124f9a8c9e51d73397176ee422a5c7ababee560194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
